eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
okta:
  oauth2:
    issuer: https://dev-45999960.okta.com/oauth2/default
    audience: api://default
    client-id: 0oa6z5o4y716F95oC5d7
    client-secret: tEzckF7BL3s0mlRrYDgiZCB8cYJ1PTHDORGa2pXO
    scopes: openid, profile, email, offline_access      
